FROM alpine:3.23

ARG TARGETPLATFORM

RUN apk add --no-cache ca-certificates tzdata git

COPY ${TARGETPLATFORM}/ored /usr/local/bin/ored

ENV ORED_ADDR=":9090"
ENV ORED_PROJECTS="/var/lib/ored/projects"
ENV XDG_CONFIG_HOME="/var/lib/ored/config"

EXPOSE 9090

VOLUME ["/var/lib/ored"]

ENTRYPOINT ["ored"]
