// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ore/v1/ore.proto

package orev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PruneTarget int32

const (
	PruneTarget_PRUNE_TARGET_UNSPECIFIED PruneTarget = 0
	PruneTarget_PRUNE_TARGET_ALL         PruneTarget = 1
	PruneTarget_PRUNE_TARGET_CONTAINERS  PruneTarget = 2
	PruneTarget_PRUNE_TARGET_IMAGES      PruneTarget = 3
	PruneTarget_PRUNE_TARGET_VOLUMES     PruneTarget = 4
)

// Enum value maps for PruneTarget.
var (
	PruneTarget_name = map[int32]string{
		0: "PRUNE_TARGET_UNSPECIFIED",
		1: "PRUNE_TARGET_ALL",
		2: "PRUNE_TARGET_CONTAINERS",
		3: "PRUNE_TARGET_IMAGES",
		4: "PRUNE_TARGET_VOLUMES",
	}
	PruneTarget_value = map[string]int32{
		"PRUNE_TARGET_UNSPECIFIED": 0,
		"PRUNE_TARGET_ALL":         1,
		"PRUNE_TARGET_CONTAINERS":  2,
		"PRUNE_TARGET_IMAGES":      3,
		"PRUNE_TARGET_VOLUMES":     4,
	}
)

func (x PruneTarget) Enum() *PruneTarget {
	p := new(PruneTarget)
	*p = x
	return p
}

func (x PruneTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PruneTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_ore_v1_ore_proto_enumTypes[0].Descriptor()
}

func (PruneTarget) Type() protoreflect.EnumType {
	return &file_ore_v1_ore_proto_enumTypes[0]
}

func (x PruneTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PruneTarget.Descriptor instead.
func (PruneTarget) EnumDescriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{0}
}

type CleanTarget int32

const (
	CleanTarget_CLEAN_TARGET_UNSPECIFIED CleanTarget = 0
	CleanTarget_CLEAN_TARGET_ALL         CleanTarget = 1
	CleanTarget_CLEAN_TARGET_CACHE       CleanTarget = 2
	CleanTarget_CLEAN_TARGET_BUILDS      CleanTarget = 3
)

// Enum value maps for CleanTarget.
var (
	CleanTarget_name = map[int32]string{
		0: "CLEAN_TARGET_UNSPECIFIED",
		1: "CLEAN_TARGET_ALL",
		2: "CLEAN_TARGET_CACHE",
		3: "CLEAN_TARGET_BUILDS",
	}
	CleanTarget_value = map[string]int32{
		"CLEAN_TARGET_UNSPECIFIED": 0,
		"CLEAN_TARGET_ALL":         1,
		"CLEAN_TARGET_CACHE":       2,
		"CLEAN_TARGET_BUILDS":      3,
	}
)

func (x CleanTarget) Enum() *CleanTarget {
	p := new(CleanTarget)
	*p = x
	return p
}

func (x CleanTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CleanTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_ore_v1_ore_proto_enumTypes[1].Descriptor()
}

func (CleanTarget) Type() protoreflect.EnumType {
	return &file_ore_v1_ore_proto_enumTypes[1]
}

func (x CleanTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CleanTarget.Descriptor instead.
func (CleanTarget) EnumDescriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{1}
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeUnixMilli int64                  `protobuf:"varint,1,opt,name=time_unix_milli,json=timeUnixMilli,proto3" json:"time_unix_milli,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Attrs         []*LogAttr             `protobuf:"bytes,4,rep,name=attrs,proto3" json:"attrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_ore_v1_ore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetTimeUnixMilli() int64 {
	if x != nil {
		return x.TimeUnixMilli
	}
	return 0
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetAttrs() []*LogAttr {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type LogAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogAttr) Reset() {
	*x = LogAttr{}
	mi := &file_ore_v1_ore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAttr) ProtoMessage() {}

func (x *LogAttr) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAttr.ProtoReflect.Descriptor instead.
func (*LogAttr) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{1}
}

func (x *LogAttr) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LogAttr) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoCache       bool                   `protobuf:"varint,1,opt,name=no_cache,json=noCache,proto3" json:"no_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpRequest) Reset() {
	*x = UpRequest{}
	mi := &file_ore_v1_ore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpRequest) ProtoMessage() {}

func (x *UpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpRequest.ProtoReflect.Descriptor instead.
func (*UpRequest) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{2}
}

func (x *UpRequest) GetNoCache() bool {
	if x != nil {
		return x.NoCache
	}
	return false
}

type UpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *LogEntry              `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpResponse) Reset() {
	*x = UpResponse{}
	mi := &file_ore_v1_ore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpResponse) ProtoMessage() {}

func (x *UpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpResponse.ProtoReflect.Descriptor instead.
func (*UpResponse) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{3}
}

func (x *UpResponse) GetLog() *LogEntry {
	if x != nil {
		return x.Log
	}
	return nil
}

type DownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownRequest) Reset() {
	*x = DownRequest{}
	mi := &file_ore_v1_ore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownRequest) ProtoMessage() {}

func (x *DownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownRequest.ProtoReflect.Descriptor instead.
func (*DownRequest) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{4}
}

type DownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *LogEntry              `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownResponse) Reset() {
	*x = DownResponse{}
	mi := &file_ore_v1_ore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownResponse) ProtoMessage() {}

func (x *DownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownResponse.ProtoReflect.Descriptor instead.
func (*DownResponse) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{5}
}

func (x *DownResponse) GetLog() *LogEntry {
	if x != nil {
		return x.Log
	}
	return nil
}

type BuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoCache       bool                   `protobuf:"varint,1,opt,name=no_cache,json=noCache,proto3" json:"no_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	mi := &file_ore_v1_ore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{6}
}

func (x *BuildRequest) GetNoCache() bool {
	if x != nil {
		return x.NoCache
	}
	return false
}

type BuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *LogEntry              `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResponse) Reset() {
	*x = BuildResponse{}
	mi := &file_ore_v1_ore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse) ProtoMessage() {}

func (x *BuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse.ProtoReflect.Descriptor instead.
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{7}
}

func (x *BuildResponse) GetLog() *LogEntry {
	if x != nil {
		return x.Log
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_ore_v1_ore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{8}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Servers       []*ServerStatus        `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_ore_v1_ore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{9}
}

func (x *StatusResponse) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *StatusResponse) GetServers() []*ServerStatus {
	if x != nil {
		return x.Servers
	}
	return nil
}

type ServerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Replicas      []*ContainerStatus     `protobuf:"bytes,2,rep,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_ore_v1_ore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{10}
}

func (x *ServerStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerStatus) GetReplicas() []*ContainerStatus {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type ContainerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Health        string                 `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Ports         []*PortBinding         `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	StartedAtUnix int64                  `protobuf:"varint,6,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,7,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	RestartCount  int32                  `protobuf:"varint,8,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	ExitCode      int32                  `protobuf:"varint,9,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,10,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Cpus          float64                `protobuf:"fixed64,11,opt,name=cpus,proto3" json:"cpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStatus) Reset() {
	*x = ContainerStatus{}
	mi := &file_ore_v1_ore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatus) ProtoMessage() {}

func (x *ContainerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatus.ProtoReflect.Descriptor instead.
func (*ContainerStatus) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{11}
}

func (x *ContainerStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerStatus) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *ContainerStatus) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerStatus) GetPorts() []*PortBinding {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ContainerStatus) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

func (x *ContainerStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ContainerStatus) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *ContainerStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContainerStatus) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ContainerStatus) GetCpus() float64 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

type PortBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostPort      int32                  `protobuf:"varint,1,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	ContainerPort int32                  `protobuf:"varint,2,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortBinding) Reset() {
	*x = PortBinding{}
	mi := &file_ore_v1_ore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortBinding) ProtoMessage() {}

func (x *PortBinding) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortBinding.ProtoReflect.Descriptor instead.
func (*PortBinding) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{12}
}

func (x *PortBinding) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PortBinding) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *PortBinding) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type PruneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        PruneTarget            `protobuf:"varint,1,opt,name=target,proto3,enum=ore.v1.PruneTarget" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneRequest) Reset() {
	*x = PruneRequest{}
	mi := &file_ore_v1_ore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneRequest) ProtoMessage() {}

func (x *PruneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneRequest.ProtoReflect.Descriptor instead.
func (*PruneRequest) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{13}
}

func (x *PruneRequest) GetTarget() PruneTarget {
	if x != nil {
		return x.Target
	}
	return PruneTarget_PRUNE_TARGET_UNSPECIFIED
}

type PruneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *LogEntry              `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneResponse) Reset() {
	*x = PruneResponse{}
	mi := &file_ore_v1_ore_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneResponse) ProtoMessage() {}

func (x *PruneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneResponse.ProtoReflect.Descriptor instead.
func (*PruneResponse) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{14}
}

func (x *PruneResponse) GetLog() *LogEntry {
	if x != nil {
		return x.Log
	}
	return nil
}

type CleanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        CleanTarget            `protobuf:"varint,1,opt,name=target,proto3,enum=ore.v1.CleanTarget" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanRequest) Reset() {
	*x = CleanRequest{}
	mi := &file_ore_v1_ore_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanRequest) ProtoMessage() {}

func (x *CleanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanRequest.ProtoReflect.Descriptor instead.
func (*CleanRequest) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{15}
}

func (x *CleanRequest) GetTarget() CleanTarget {
	if x != nil {
		return x.Target
	}
	return CleanTarget_CLEAN_TARGET_UNSPECIFIED
}

type CleanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *LogEntry              `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanResponse) Reset() {
	*x = CleanResponse{}
	mi := &file_ore_v1_ore_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanResponse) ProtoMessage() {}

func (x *CleanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanResponse.ProtoReflect.Descriptor instead.
func (*CleanResponse) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{16}
}

func (x *CleanResponse) GetLog() *LogEntry {
	if x != nil {
		return x.Log
	}
	return nil
}

type ConsoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Replica       int32                  `protobuf:"varint,2,opt,name=replica,proto3" json:"replica,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleRequest) Reset() {
	*x = ConsoleRequest{}
	mi := &file_ore_v1_ore_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleRequest) ProtoMessage() {}

func (x *ConsoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleRequest.ProtoReflect.Descriptor instead.
func (*ConsoleRequest) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{17}
}

func (x *ConsoleRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ConsoleRequest) GetReplica() int32 {
	if x != nil {
		return x.Replica
	}
	return 0
}

type ConsoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Nonce         string                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleResponse) Reset() {
	*x = ConsoleResponse{}
	mi := &file_ore_v1_ore_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleResponse) ProtoMessage() {}

func (x *ConsoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleResponse.ProtoReflect.Descriptor instead.
func (*ConsoleResponse) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{18}
}

func (x *ConsoleResponse) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ConsoleResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_ore_v1_ore_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{19}
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []string               `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_ore_v1_ore_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ore_v1_ore_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_ore_v1_ore_proto_rawDescGZIP(), []int{20}
}

func (x *ListProjectsResponse) GetProjects() []string {
	if x != nil {
		return x.Projects
	}
	return nil
}

var File_ore_v1_ore_proto protoreflect.FileDescriptor

const file_ore_v1_ore_proto_rawDesc = "" +
	"\n" +
	"\x10ore/v1/ore.proto\x12\x06ore.v1\"\x89\x01\n" +
	"\bLogEntry\x12&\n" +
	"\x0ftime_unix_milli\x18\x01 \x01(\x03R\rtimeUnixMilli\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12%\n" +
	"\x05attrs\x18\x04 \x03(\v2\x0f.ore.v1.LogAttrR\x05attrs\"1\n" +
	"\aLogAttr\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"&\n" +
	"\tUpRequest\x12\x19\n" +
	"\bno_cache\x18\x01 \x01(\bR\anoCache\"0\n" +
	"\n" +
	"UpResponse\x12\"\n" +
	"\x03log\x18\x01 \x01(\v2\x10.ore.v1.LogEntryR\x03log\"\r\n" +
	"\vDownRequest\"2\n" +
	"\fDownResponse\x12\"\n" +
	"\x03log\x18\x01 \x01(\v2\x10.ore.v1.LogEntryR\x03log\")\n" +
	"\fBuildRequest\x12\x19\n" +
	"\bno_cache\x18\x01 \x01(\bR\anoCache\"3\n" +
	"\rBuildResponse\x12\"\n" +
	"\x03log\x18\x01 \x01(\v2\x10.ore.v1.LogEntryR\x03log\"\x0f\n" +
	"\rStatusRequest\"Z\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12.\n" +
	"\aservers\x18\x02 \x03(\v2\x14.ore.v1.ServerStatusR\aservers\"W\n" +
	"\fServerStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\breplicas\x18\x02 \x03(\v2\x17.ore.v1.ContainerStatusR\breplicas\"\xdc\x02\n" +
	"\x0fContainerStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x16\n" +
	"\x06health\x18\x03 \x01(\tR\x06health\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12)\n" +
	"\x05ports\x18\x05 \x03(\v2\x13.ore.v1.PortBindingR\x05ports\x12&\n" +
	"\x0fstarted_at_unix\x18\x06 \x01(\x03R\rstartedAtUnix\x12%\n" +
	"\x0euptime_seconds\x18\a \x01(\x03R\ruptimeSeconds\x12#\n" +
	"\rrestart_count\x18\b \x01(\x05R\frestartCount\x12\x1b\n" +
	"\texit_code\x18\t \x01(\x05R\bexitCode\x12!\n" +
	"\fmemory_bytes\x18\n" +
	" \x01(\x03R\vmemoryBytes\x12\x12\n" +
	"\x04cpus\x18\v \x01(\x01R\x04cpus\"m\n" +
	"\vPortBinding\x12\x1b\n" +
	"\thost_port\x18\x01 \x01(\x05R\bhostPort\x12%\n" +
	"\x0econtainer_port\x18\x02 \x01(\x05R\rcontainerPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\";\n" +
	"\fPruneRequest\x12+\n" +
	"\x06target\x18\x01 \x01(\x0e2\x13.ore.v1.PruneTargetR\x06target\"3\n" +
	"\rPruneResponse\x12\"\n" +
	"\x03log\x18\x01 \x01(\v2\x10.ore.v1.LogEntryR\x03log\";\n" +
	"\fCleanRequest\x12+\n" +
	"\x06target\x18\x01 \x01(\x0e2\x13.ore.v1.CleanTargetR\x06target\"3\n" +
	"\rCleanResponse\x12\"\n" +
	"\x03log\x18\x01 \x01(\v2\x10.ore.v1.LogEntryR\x03log\"K\n" +
	"\x0eConsoleRequest\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12\x18\n" +
	"\areplica\x18\x02 \x01(\x05R\areplica\";\n" +
	"\x0fConsoleResponse\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\"\x15\n" +
	"\x13ListProjectsRequest\"2\n" +
	"\x14ListProjectsResponse\x12\x1a\n" +
	"\bprojects\x18\x01 \x03(\tR\bprojects*\x91\x01\n" +
	"\vPruneTarget\x12\x1c\n" +
	"\x18PRUNE_TARGET_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PRUNE_TARGET_ALL\x10\x01\x12\x1b\n" +
	"\x17PRUNE_TARGET_CONTAINERS\x10\x02\x12\x17\n" +
	"\x13PRUNE_TARGET_IMAGES\x10\x03\x12\x18\n" +
	"\x14PRUNE_TARGET_VOLUMES\x10\x04*r\n" +
	"\vCleanTarget\x12\x1c\n" +
	"\x18CLEAN_TARGET_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CLEAN_TARGET_ALL\x10\x01\x12\x16\n" +
	"\x12CLEAN_TARGET_CACHE\x10\x02\x12\x17\n" +
	"\x13CLEAN_TARGET_BUILDS\x10\x032\xd8\x03\n" +
	"\n" +
	"OreService\x12-\n" +
	"\x02Up\x12\x11.ore.v1.UpRequest\x1a\x12.ore.v1.UpResponse0\x01\x123\n" +
	"\x04Down\x12\x13.ore.v1.DownRequest\x1a\x14.ore.v1.DownResponse0\x01\x126\n" +
	"\x05Build\x12\x14.ore.v1.BuildRequest\x1a\x15.ore.v1.BuildResponse0\x01\x127\n" +
	"\x06Status\x12\x15.ore.v1.StatusRequest\x1a\x16.ore.v1.StatusResponse\x126\n" +
	"\x05Prune\x12\x14.ore.v1.PruneRequest\x1a\x15.ore.v1.PruneResponse0\x01\x126\n" +
	"\x05Clean\x12\x14.ore.v1.CleanRequest\x1a\x15.ore.v1.CleanResponse0\x01\x12:\n" +
	"\aConsole\x12\x16.ore.v1.ConsoleRequest\x1a\x17.ore.v1.ConsoleResponse\x12I\n" +
	"\fListProjects\x12\x1b.ore.v1.ListProjectsRequest\x1a\x1c.ore.v1.ListProjectsResponseB#Z!github.com/oreforge/ore/api/orev1b\x06proto3"

var (
	file_ore_v1_ore_proto_rawDescOnce sync.Once
	file_ore_v1_ore_proto_rawDescData []byte
)

func file_ore_v1_ore_proto_rawDescGZIP() []byte {
	file_ore_v1_ore_proto_rawDescOnce.Do(func() {
		file_ore_v1_ore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ore_v1_ore_proto_rawDesc), len(file_ore_v1_ore_proto_rawDesc)))
	})
	return file_ore_v1_ore_proto_rawDescData
}

var file_ore_v1_ore_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ore_v1_ore_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_ore_v1_ore_proto_goTypes = []any{
	(PruneTarget)(0),             // 0: ore.v1.PruneTarget
	(CleanTarget)(0),             // 1: ore.v1.CleanTarget
	(*LogEntry)(nil),             // 2: ore.v1.LogEntry
	(*LogAttr)(nil),              // 3: ore.v1.LogAttr
	(*UpRequest)(nil),            // 4: ore.v1.UpRequest
	(*UpResponse)(nil),           // 5: ore.v1.UpResponse
	(*DownRequest)(nil),          // 6: ore.v1.DownRequest
	(*DownResponse)(nil),         // 7: ore.v1.DownResponse
	(*BuildRequest)(nil),         // 8: ore.v1.BuildRequest
	(*BuildResponse)(nil),        // 9: ore.v1.BuildResponse
	(*StatusRequest)(nil),        // 10: ore.v1.StatusRequest
	(*StatusResponse)(nil),       // 11: ore.v1.StatusResponse
	(*ServerStatus)(nil),         // 12: ore.v1.ServerStatus
	(*ContainerStatus)(nil),      // 13: ore.v1.ContainerStatus
	(*PortBinding)(nil),          // 14: ore.v1.PortBinding
	(*PruneRequest)(nil),         // 15: ore.v1.PruneRequest
	(*PruneResponse)(nil),        // 16: ore.v1.PruneResponse
	(*CleanRequest)(nil),         // 17: ore.v1.CleanRequest
	(*CleanResponse)(nil),        // 18: ore.v1.CleanResponse
	(*ConsoleRequest)(nil),       // 19: ore.v1.ConsoleRequest
	(*ConsoleResponse)(nil),      // 20: ore.v1.ConsoleResponse
	(*ListProjectsRequest)(nil),  // 21: ore.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil), // 22: ore.v1.ListProjectsResponse
}
var file_ore_v1_ore_proto_depIdxs = []int32{
	3,  // 0: ore.v1.LogEntry.attrs:type_name -> ore.v1.LogAttr
	2,  // 1: ore.v1.UpResponse.log:type_name -> ore.v1.LogEntry
	2,  // 2: ore.v1.DownResponse.log:type_name -> ore.v1.LogEntry
	2,  // 3: ore.v1.BuildResponse.log:type_name -> ore.v1.LogEntry
	12, // 4: ore.v1.StatusResponse.servers:type_name -> ore.v1.ServerStatus
	13, // 5: ore.v1.ServerStatus.replicas:type_name -> ore.v1.ContainerStatus
	14, // 6: ore.v1.ContainerStatus.ports:type_name -> ore.v1.PortBinding
	0,  // 7: ore.v1.PruneRequest.target:type_name -> ore.v1.PruneTarget
	2,  // 8: ore.v1.PruneResponse.log:type_name -> ore.v1.LogEntry
	1,  // 9: ore.v1.CleanRequest.target:type_name -> ore.v1.CleanTarget
	2,  // 10: ore.v1.CleanResponse.log:type_name -> ore.v1.LogEntry
	4,  // 11: ore.v1.OreService.Up:input_type -> ore.v1.UpRequest
	6,  // 12: ore.v1.OreService.Down:input_type -> ore.v1.DownRequest
	8,  // 13: ore.v1.OreService.Build:input_type -> ore.v1.BuildRequest
	10, // 14: ore.v1.OreService.Status:input_type -> ore.v1.StatusRequest
	15, // 15: ore.v1.OreService.Prune:input_type -> ore.v1.PruneRequest
	17, // 16: ore.v1.OreService.Clean:input_type -> ore.v1.CleanRequest
	19, // 17: ore.v1.OreService.Console:input_type -> ore.v1.ConsoleRequest
	21, // 18: ore.v1.OreService.ListProjects:input_type -> ore.v1.ListProjectsRequest
	5,  // 19: ore.v1.OreService.Up:output_type -> ore.v1.UpResponse
	7,  // 20: ore.v1.OreService.Down:output_type -> ore.v1.DownResponse
	9,  // 21: ore.v1.OreService.Build:output_type -> ore.v1.BuildResponse
	11, // 22: ore.v1.OreService.Status:output_type -> ore.v1.StatusResponse
	16, // 23: ore.v1.OreService.Prune:output_type -> ore.v1.PruneResponse
	18, // 24: ore.v1.OreService.Clean:output_type -> ore.v1.CleanResponse
	20, // 25: ore.v1.OreService.Console:output_type -> ore.v1.ConsoleResponse
	22, // 26: ore.v1.OreService.ListProjects:output_type -> ore.v1.ListProjectsResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_ore_v1_ore_proto_init() }
func file_ore_v1_ore_proto_init() {
	if File_ore_v1_ore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ore_v1_ore_proto_rawDesc), len(file_ore_v1_ore_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ore_v1_ore_proto_goTypes,
		DependencyIndexes: file_ore_v1_ore_proto_depIdxs,
		EnumInfos:         file_ore_v1_ore_proto_enumTypes,
		MessageInfos:      file_ore_v1_ore_proto_msgTypes,
	}.Build()
	File_ore_v1_ore_proto = out.File
	file_ore_v1_ore_proto_goTypes = nil
	file_ore_v1_ore_proto_depIdxs = nil
}
