// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: ore/v1/ore.proto

package orev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OreService_Up_FullMethodName           = "/ore.v1.OreService/Up"
	OreService_Down_FullMethodName         = "/ore.v1.OreService/Down"
	OreService_Build_FullMethodName        = "/ore.v1.OreService/Build"
	OreService_Status_FullMethodName       = "/ore.v1.OreService/Status"
	OreService_Prune_FullMethodName        = "/ore.v1.OreService/Prune"
	OreService_Clean_FullMethodName        = "/ore.v1.OreService/Clean"
	OreService_Console_FullMethodName      = "/ore.v1.OreService/Console"
	OreService_ListProjects_FullMethodName = "/ore.v1.OreService/ListProjects"
)

// OreServiceClient is the client API for OreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OreServiceClient interface {
	Up(ctx context.Context, in *UpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpResponse], error)
	Down(ctx context.Context, in *DownRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownResponse], error)
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BuildResponse], error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Prune(ctx context.Context, in *PruneRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PruneResponse], error)
	Clean(ctx context.Context, in *CleanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CleanResponse], error)
	Console(ctx context.Context, in *ConsoleRequest, opts ...grpc.CallOption) (*ConsoleResponse, error)
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
}

type oreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOreServiceClient(cc grpc.ClientConnInterface) OreServiceClient {
	return &oreServiceClient{cc}
}

func (c *oreServiceClient) Up(ctx context.Context, in *UpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OreService_ServiceDesc.Streams[0], OreService_Up_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpRequest, UpResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OreService_UpClient = grpc.ServerStreamingClient[UpResponse]

func (c *oreServiceClient) Down(ctx context.Context, in *DownRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OreService_ServiceDesc.Streams[1], OreService_Down_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownRequest, DownResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OreService_DownClient = grpc.ServerStreamingClient[DownResponse]

func (c *oreServiceClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BuildResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OreService_ServiceDesc.Streams[2], OreService_Build_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BuildRequest, BuildResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OreService_BuildClient = grpc.ServerStreamingClient[BuildResponse]

func (c *oreServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, OreService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oreServiceClient) Prune(ctx context.Context, in *PruneRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PruneResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OreService_ServiceDesc.Streams[3], OreService_Prune_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PruneRequest, PruneResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OreService_PruneClient = grpc.ServerStreamingClient[PruneResponse]

func (c *oreServiceClient) Clean(ctx context.Context, in *CleanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CleanResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OreService_ServiceDesc.Streams[4], OreService_Clean_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CleanRequest, CleanResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OreService_CleanClient = grpc.ServerStreamingClient[CleanResponse]

func (c *oreServiceClient) Console(ctx context.Context, in *ConsoleRequest, opts ...grpc.CallOption) (*ConsoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsoleResponse)
	err := c.cc.Invoke(ctx, OreService_Console_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oreServiceClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, OreService_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OreServiceServer is the server API for OreService service.
// All implementations must embed UnimplementedOreServiceServer
// for forward compatibility.
type OreServiceServer interface {
	Up(*UpRequest, grpc.ServerStreamingServer[UpResponse]) error
	Down(*DownRequest, grpc.ServerStreamingServer[DownResponse]) error
	Build(*BuildRequest, grpc.ServerStreamingServer[BuildResponse]) error
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	Prune(*PruneRequest, grpc.ServerStreamingServer[PruneResponse]) error
	Clean(*CleanRequest, grpc.ServerStreamingServer[CleanResponse]) error
	Console(context.Context, *ConsoleRequest) (*ConsoleResponse, error)
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error)
	mustEmbedUnimplementedOreServiceServer()
}

// UnimplementedOreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOreServiceServer struct{}

func (UnimplementedOreServiceServer) Up(*UpRequest, grpc.ServerStreamingServer[UpResponse]) error {
	return status.Error(codes.Unimplemented, "method Up not implemented")
}
func (UnimplementedOreServiceServer) Down(*DownRequest, grpc.ServerStreamingServer[DownResponse]) error {
	return status.Error(codes.Unimplemented, "method Down not implemented")
}
func (UnimplementedOreServiceServer) Build(*BuildRequest, grpc.ServerStreamingServer[BuildResponse]) error {
	return status.Error(codes.Unimplemented, "method Build not implemented")
}
func (UnimplementedOreServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedOreServiceServer) Prune(*PruneRequest, grpc.ServerStreamingServer[PruneResponse]) error {
	return status.Error(codes.Unimplemented, "method Prune not implemented")
}
func (UnimplementedOreServiceServer) Clean(*CleanRequest, grpc.ServerStreamingServer[CleanResponse]) error {
	return status.Error(codes.Unimplemented, "method Clean not implemented")
}
func (UnimplementedOreServiceServer) Console(context.Context, *ConsoleRequest) (*ConsoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Console not implemented")
}
func (UnimplementedOreServiceServer) ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedOreServiceServer) mustEmbedUnimplementedOreServiceServer() {}
func (UnimplementedOreServiceServer) testEmbeddedByValue()                    {}

// UnsafeOreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OreServiceServer will
// result in compilation errors.
type UnsafeOreServiceServer interface {
	mustEmbedUnimplementedOreServiceServer()
}

func RegisterOreServiceServer(s grpc.ServiceRegistrar, srv OreServiceServer) {
	// If the following call panics, it indicates UnimplementedOreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OreService_ServiceDesc, srv)
}

func _OreService_Up_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UpRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OreServiceServer).Up(m, &grpc.GenericServerStream[UpRequest, UpResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OreService_UpServer = grpc.ServerStreamingServer[UpResponse]

func _OreService_Down_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OreServiceServer).Down(m, &grpc.GenericServerStream[DownRequest, DownResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OreService_DownServer = grpc.ServerStreamingServer[DownResponse]

func _OreService_Build_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OreServiceServer).Build(m, &grpc.GenericServerStream[BuildRequest, BuildResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OreService_BuildServer = grpc.ServerStreamingServer[BuildResponse]

func _OreService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OreServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OreService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OreServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OreService_Prune_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PruneRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OreServiceServer).Prune(m, &grpc.GenericServerStream[PruneRequest, PruneResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OreService_PruneServer = grpc.ServerStreamingServer[PruneResponse]

func _OreService_Clean_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CleanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OreServiceServer).Clean(m, &grpc.GenericServerStream[CleanRequest, CleanResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OreService_CleanServer = grpc.ServerStreamingServer[CleanResponse]

func _OreService_Console_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OreServiceServer).Console(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OreService_Console_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OreServiceServer).Console(ctx, req.(*ConsoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OreService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OreServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OreService_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OreServiceServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OreService_ServiceDesc is the grpc.ServiceDesc for OreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ore.v1.OreService",
	HandlerType: (*OreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _OreService_Status_Handler,
		},
		{
			MethodName: "Console",
			Handler:    _OreService_Console_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _OreService_ListProjects_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Up",
			Handler:       _OreService_Up_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Down",
			Handler:       _OreService_Down_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Build",
			Handler:       _OreService_Build_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Prune",
			Handler:       _OreService_Prune_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Clean",
			Handler:       _OreService_Clean_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ore/v1/ore.proto",
}
